### ISSUE TITLE
AWS Tests

### ISSUE THREAD

**Issue by samoconnor** [JuliaCI/PackageEvaluator.jl#119]
AWSCore.jl (and AWS*.jl) are marked as failing:

http://pkg.julialang.org/detail/AWSCore.html

These tests pass on Travis with Julia 0.4.2.

https://travis-ci.org/samoconnor/AWSCore.jl
https://travis-ci.org/samoconnor/AWSEC2.jl
https://travis-ci.org/samoconnor/AWSIAM.jl
https://travis-ci.org/samoconnor/AWSS3.jl
https://travis-ci.org/samoconnor/AWSSNS.jl
https://travis-ci.org/samoconnor/AWSSQS.jl

The failure is because PackageEvaluator.jl cannot support the [encrypted environment variables in the .travis.yml file](https://github.com/samoconnor/AWSCore.jl/blob/master/.travis.yml#L14), so the tests don't have any credentials with which to connect to AWS.

Can I configure the package so that PackageEvaluator.jl will just show the Travis test results?
I assume that PackageEvaluator.jl has no secure mechanism for passing encrypted data to the test code.

**Comment by IainNZ** [comment]
We don't have any mechanism for passing encrypted data or anything like that.

You can't configure it to use the Travis results (that would also defeat the point), but you can submit a PR to update the list of exclusions so that AWS*.jl is marked as untestable on PkgEval:
https://github.com/JuliaCI/PackageEvaluator.jl/blob/master/src/constants.jl

**Comment by samoconnor** [comment]
> that would also defeat the point

I'm curious, what is the point of PackageEvaluator.jl using a different CI framework when Travis seems to be more feature-full?

**Comment by IainNZ** [comment]
Because PackageEvaluator doesn't run when you make a commit, it runs (ideally) every day - and catches packages that now fail on newer Julia versions, or when a dependency breaks, etc. If you are actively developing your package, it has little utility to you, but once you stop its utility increases (and increases to the end user as well).

**Comment by samoconnor** [comment]
Is there a cost reason for not running Travis on a schedule? (e.g. nightly if dependancies have changed).

**Comment by IainNZ** [comment]
I don't understand, how would I test your package on Travis?

**Comment by samoconnor** [comment]
I admit, I'm not intimately familiar with the details, but the Travis API has a way of triggering builds with a POST request: https://docs.travis-ci.com/user/triggering-builds

I guess the PackageEvaluator.jl website could have a form where the package developer registers a Travis token for the package, thereby delegating the ability to trigger builds.

**Comment by IainNZ** [comment]
Thats not something I'm interested in working on, and isn't really how we're using PkgEval right now, but feel free to fork this and work on that.

I'm going to close this now, looking forward to a PR regarding the AWS*.jl packages.

**Comment by IainNZ** [comment]
Bump for the PR

**Comment by IainNZ** [comment]
Closed by
https://github.com/JuliaCI/PackageEvaluator.jl/commit/2b059fe03f9e0b7f3b3627f145cad32a31d4cdae
