### ISSUE TITLE
"Top twenty all-time" does not list 20 packages.

### ISSUE THREAD

**Issue by bicycle1885** [JuliaCI/PackageEvaluator.jl#148]
I noticed today that "Top twenty all-time" only lists 11 packages [there](http://pkg.julialang.org/pulse.html):

![screen shot 2016-10-18 at 17 30 52](https://cloud.githubusercontent.com/assets/905683/19470029/eab7e1aa-9558-11e6-8e7a-b7cf4ba09b10.png)

This is sad to me because our lovely package, Bio.jl, is out of scope (it is ranked at 19, IIRC).

**Comment by tkelman** [comment]
Should be happening here https://github.com/JuliaCI/PackageEvaluator.jl/blob/82275426350fcda870e89901cd78cd424c7ebe21/website/build_pulse.jl#L136-L152

I'll check the logs.

**Comment by tkelman** [comment]
I see the issue. Looks like there are a bunch of failures on nightly due to ssl certificate issues that we're in the middle of hopefully fixing. Gadfly, DataFrames, JuMP, Escher, DSGE, Distributions, Bio, Morsel, GLM, TensorFlow, Images, and LightGraphs are all giving warnings that they're missing, probably because they either failed tests or couldn't even be installed to start running tests so no data was recorded. I'll change the star criteria to be based on 0.5 results, which should be more stable. I don't think we have any 0.6-only packages yet.

**Comment by bicycle1885** [comment]
What a rapid fix! Thank you!

**Comment by tkelman** [comment]
No problem. Will have to wait until the next time the pulse gets re-generated to be reflected on the site, should be within a day.

**Comment by tkelman** [comment]
it's showing 19 now, I thin because Morsel still has a lot of stars despite having been deprecated for a long time

**Comment by bicycle1885** [comment]
Thank you. Yes, it seems to be.
