### ISSUE TITLE
green badge if PkgEval times out and no errors so far

### ISSUE THREAD

**Issue by bjarthur** [JuliaCI/PackageEvaluator.jl#198]
we shouldn't penalize packages with extensive unit tests with a red badge.  happy to work on a PR if there is a consensus.

**Comment by tkelman** [comment]
How do you intend to implement this?

**Comment by ararslan** [comment]
I don't think it's really appropriate to declare that a package is passing its tests if the tests time out before finishing. Could be that whatever caused them to time out, or anything that would run afterward, would fail.

**Comment by bjarthur** [comment]
how about a yellow badge then if it times out?

it seems very bad to me to discourage thorough unit testing.

**Comment by Nosferican** [comment]
An alternative would be to have smaller packages, test the components and just have the production ready package call them.

**Comment by IainNZ** [comment]
What is the package in question?
How long do the tests take to run?
Is that likely to change?

Adding complexity for a "timed out" is a feature request. If you'd be willing to implement such a feature, please re-open and we can discuss further. Otherwise, I suggest going the "untestable on pkgeval route".
